services:
  postgres:
    image: postgres:14-alpine
    container_name: app-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  grupoa:
    build:
      context: ./grupoa
      dockerfile: Dockerfile
    container_name: app-grupoa
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    env_file:
      - ./grupoa/.env

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: app-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - grupoa

volumes:
  postgres-data: